name: Sync Folder to New Repo

on:
  push:
    paths:
      - 'Assets/VRExplorer/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Prepare and sync folder
        run: |
          set -e  # 脚本中出错即终止

          # 设置变量
          FOLDER_PATH="Assets/VRExplorer"
          NEW_REPO="VRExplorer_Release"
          NEW_REPO_URL="https://${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$NEW_REPO.git"

          # 创建临时目录
          TEMP_DIR="$(mktemp -d)"
          echo "Using temp directory: $TEMP_DIR"

          # 拷贝目标文件夹内容到临时目录
          cp -r "$FOLDER_PATH/"* "$TEMP_DIR"

          # 初始化新 Git 仓库
          cd "$TEMP_DIR"
          git init -b main
          git remote add origin "$NEW_REPO_URL"
          git add .
          git commit -m "Sync from $FOLDER_PATH at $(date -u)"
          git push origin main --force
