name: Sync Folder
on:
  push:
    paths:
      - 'Assets/VRExplorer/**' # 监听子内容的变化
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Check if new repository exists
        id: check_repo
        run: |
          NEW_REPO="VRExplorer_Release"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/$NEW_REPO)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create new repository if not exists
        if: steps.check_repo.outputs.exists == 'false'
        run: |
          NEW_REPO="VRExplorer_Release"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            https://api.github.com/user/repos \
            -d '{"name":"'$NEW_REPO'", "private":false}'

      - name: Sync folder contents to new repository
        run: |
          # 设置变量
          FOLDER_PATH="Assets/VRExplorer"
          NEW_REPO="VRExplorer_Release"
          NEW_REPO_URL="https://${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$NEW_REPO.git"

          # 创建新文件夹并复制子内容
          mkdir $NEW_REPO
          cp -r "$FOLDER_PATH"/* "$NEW_REPO/"

          # 初始化 Git 并推送
          cd $NEW_REPO
          git init -b main  # 初始化并指定默认分支为 main
          git add .
          git commit -m "Synced folder from original repo"
          git remote add origin $NEW_REPO_URL
          git push -u origin main --force
